version: '3.9'
services:
  db:
    image: mongo
    container_name: mongo-test
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=meytar
      - MONGO_INITDB_ROOT_PASSWORD=phonebook
  db-client:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=meytar
      - ME_CONFIG_MONGODB_ADMINPASSWORD=phonebook
      - ME_CONFIG_MONGODB_URL=mongodb://meytar:phonebook@db:27017/
    depends_on:
      - db
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - db

